In [ ]:
import pandas as pd
import numpy as np

# Load the CSV file without headers
df = pd.read_csv('population.csv', header=None)

# assign column names
df.columns = ['Constituencies', 'Total Population', 'Male Population', 'Female Population']

# Save update
df.to_csv('population.csv', index=False)

In [6]:
df.head(10)

   Constituencies  Total Population  Male Population  Female Population
0  Constituencies  Total Population  Male Population  Female Population
1    NAIROBI CITY         4,397,073        2,192,452          2,204,376
2       DAGORETTI           434,208          217,651            216,526
3        EMBAKASI           988,808          492,476            496,270
4       KAMUKUNJI           268,276          136,670            131,599
5        KASARANI           780,656          381,234            399,385
6           KIBRA           185,777           94,199             91,569
7         LANGATA           197,489           96,698            100,774
8        MAKADARA           189,536           96,369             93,157
9         MATHARE           206,564          106,522            100,028

In [5]:
df.columns

Index(['Constituencies', 'Total Population', 'Male Population',
       'Female Population'],
      dtype='object')

In [9]:
# Load the Nairobi health facilities data
nairobi_data = pd.read_csv('nairobi_data.csv')

# Load the Nairobi population data
nairobi_population = pd.read_csv('population.csv')

In [10]:
# checking unique values
print(nairobi_data['Constituency'].unique())

['mathare' "lang'ata" 'kibra' 'starehe' 'westlands' 'embakasi east'
 'ruaraka' 'roysambu' 'kamukunji' 'makadara' 'dagoretti north' 'kasarani'
 'embakasi west' 'embakasi central' 'embakasi south' 'embakasi north'
 'dagoretti south']

In [11]:
#check unique values
print(nairobi_population['Constituencies'].unique())

['NAIROBI CITY' 'DAGORETTI' 'EMBAKASI' 'KAMUKUNJI' 'KASARANI' 'KIBRA'
 'LANGATA' 'MAKADARA' 'MATHARE' 'NJIRU' 'STAREHE' 'WESTLANDS']

In [13]:
# Create a new column 'Mapped_Constituency' to map constituency names
nairobi_data['Mapped_Constituency'] = nairobi_data['Constituency'].replace({
    'ruaraka': 'kasarani',
    'roysambu': 'kasarani',
    'dagoretti north': 'dagoretti',
    'dagoretti south': 'dagoretti',
    'embakasi east': 'embakasi',
    'embakasi west': 'embakasi',
    'embakasi central': 'embakasi',
    'embakasi south': 'embakasi',
    'embakasi north': 'embakasi',
    "lang'ata": 'langata' 

})

# confirm mapping
print(nairobi_data['Mapped_Constituency'].unique())

['mathare' 'langata' 'kibra' 'starehe' 'westlands' 'embakasi' 'kasarani'
 'kamukunji' 'makadara' 'dagoretti']

In [14]:
#join both data sets
facilities_data = pd.merge(
    nairobi_data,
    nairobi_population,
    left_on=nairobi_data['Mapped_Constituency'].str.upper(),  # Convert to uppercase during the join
    right_on='Constituencies',
    how='inner'
)

# Check the first few rows of the merged dataset
facilities_data.head()

,Facility Code,Facility Name,Division,Type,Owner,Location,Constituency,Beds,Cots,Job Title of in Charge,...,ART,C-IMCI,FP,HBC,IPD,Mapped_Constituency,Constituencies,Total Population,Male Population,Female Population
0,19310,st jude's huruma community health services,huruma,medical clinic,private practice - unspecified,huruma,mathare,0,0,clinical officer,...,n,n,n,n,n,mathare,MATHARE,"206,564","106,522","100,028"
1,13043,7kr mrs health centre,lang'ata,health centre,armed forces,mugumoini,lang'ata,14,0,nursing officer in charge,...,n,y,y,y,y,langata,LANGATA,"197,489","96,698","100,774"
2,20346,aar adams health centre,woodley,medical clinic,private practice - general practitioner,woodley,kibra,0,0,medical superintendant,...,n,n,n,n,n,kibra,KIBRA,"185,777","94,199","91,569"
3,12861,aar city centre clinic,starehe,medical clinic,private enterprise (institution),central business district,starehe,0,0,doctor in charge,...,n,n,y,n,y,starehe,STAREHE,"210,423","109,173","101,238"
4,16796,aar clinic sarit centre (westlands),parklands,medical clinic,private enterprise (institution),parklands,westlands,0,0,nursing officer in charge,...,n,n,n,n,n,westlands,WESTLANDS,"308,854","153,818","155,021"

In [15]:
#save to csv
facilities_data.to_csv('facilities_data.csv', index=False)

In [16]:
facilities_data.head(5)

,Facility Code,Facility Name,Division,Type,Owner,Location,Constituency,Beds,Cots,Job Title of in Charge,...,ART,C-IMCI,FP,HBC,IPD,Mapped_Constituency,Constituencies,Total Population,Male Population,Female Population
0,19310,st jude's huruma community health services,huruma,medical clinic,private practice - unspecified,huruma,mathare,0,0,clinical officer,...,n,n,n,n,n,mathare,MATHARE,"206,564","106,522","100,028"
1,13043,7kr mrs health centre,lang'ata,health centre,armed forces,mugumoini,lang'ata,14,0,nursing officer in charge,...,n,y,y,y,y,langata,LANGATA,"197,489","96,698","100,774"
2,20346,aar adams health centre,woodley,medical clinic,private practice - general practitioner,woodley,kibra,0,0,medical superintendant,...,n,n,n,n,n,kibra,KIBRA,"185,777","94,199","91,569"
3,12861,aar city centre clinic,starehe,medical clinic,private enterprise (institution),central business district,starehe,0,0,doctor in charge,...,n,n,y,n,y,starehe,STAREHE,"210,423","109,173","101,238"
4,16796,aar clinic sarit centre (westlands),parklands,medical clinic,private enterprise (institution),parklands,westlands,0,0,nursing officer in charge,...,n,n,n,n,n,westlands,WESTLANDS,"308,854","153,818","155,021"